# LEMP -> Amazon Linux
# nginx, mariadb105-server, php, php-fpm
---
- name: Install LEMP stack on Amazon Linux
  hosts: localhost
  become: yes

  tasks:
    # install nginx
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    # install mariadb
    - name: Install mariadb server
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    # install php and php-fpm
    - name: Install PHP packages
      ansible.builtin.dnf:
        name:
          - php
          - php-fpm
          - php-mysqlnd
        state: present

    # start and enable nginx
    - name: Start and enable nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: true

    # start and enable mariadb
    - name: Start and enable mariadb
      ansible.builtin.systemd_service:
        name: mariadb
        state: started
        enabled: true

    # start and enable php-fpm
    - name: Start and enable php-fpm
      ansible.builtin.systemd_service:
        name: php-fpm
        state: started
        enabled: true
